version: '2'
services:
  redis:
    image: redis:alpine
  ab:
    image: ab
    volumes:
      - ./ab.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/var/www/html
      - ./htpasswd:/etc/nginx/htpasswd
    links:
      - redis
    ports:
      - "0.0.0.0:8011:80"

