version: '2'
services:
  ab:
    image: hawkeye:ab
    volumes:
      - ./data:/data
      - ./dist:/var/www/html
      - ./htpasswd:/etc/nginx/htpasswd
    environment:
      - INTERVAL=60
    ports:
      - "0.0.0.0:8032:80"

