version: '2'
services:
  ab:
    image: lloydzhou/ab:kvrocks
    volumes:
      - ./data:/data
      - ./htpasswd:/etc/nginx/htpasswd
    environment:
      - INTERVAL=60
    ports:
      - "0.0.0.0:8032:80"

